@isTest
public class ManageAccountPageTest{
    
    //this testmethod tests the successful search on ManageContactsPage
   /* public static testmethod void testManageContactExtension(){
    ApexPages.StandardController sc=new ApexPages.StandardController();
    ManageContactExtension objTest=new ManageContactExtension();  
    objTest.lstAccount=createTestData.AccountData();
    
    objTest.searchName='anjali';
    objTest.performSearch();
    System.assertEquals(lstAccount[0],objTest.searchList[0]);
    
    }*/
}